# All config params can be found here https://docs.gauge.sh/usage/configuration#tach-toml

interfaces = []
exclude = [
  "**/*__pycache__",
  "**/*egg-info",
  "**/docs",
  "**/tests",
  "**/venv",
  "**/.venv",
  "**/conftest.py",
]
external.exclude = ["typer"]
source_roots = ["src"]
forbid_circular_dependencies = true
root_module = "allow"

[[modules]]
path = "nova.settings"
depends_on = ["nova.common", "nova.utils", "nova.config"]

[[modules]]
path = "nova.constants"
depends_on = []

[[modules]]
path = "nova.common"
depends_on = ["nova.constants", "nova.utils"]

# [[modules]]
# path = "nova.utils.logging"
# depends_on = ["nova.common", "nova.constants"]

[[modules]]
path = "nova.utils"
depends_on = ["nova.constants"]

[[modules]]
path = "nova.datastore"
depends_on = ["nova.utils", "nova.common"]

[[modules]]
path = "nova.config"

[[modules]]
path = "nova.marketplace"
depends_on = ["nova.utils", "nova.datastore", "nova.common"]

[[modules]]
path = "nova.cli"

[[modules]]
path = "<root>"
depends_on = ["nova.common"]
