# Just examples are here: https://github.com/casey/just/tree/master/examples
# Just docs are here: https://just.systems/man/en/introduction.html

# List all recipes
default:
    @just --list --unsorted


###############################################
############ Dependency Enforcement ###########
###############################################

# Sync the project's dependencies with the environment.
[group('dependency enforcement')]
sync:
    uv sync --all-extras --dev

# Upgrade all deps to latest version 
[group('dependency enforcement')]
dep-upgrade:
  uv lock --upgrade && uv sync
