[project]
name = "playground"
version = "0.1.0"
description = "Experimental notebooks for Nova development"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[dependency-groups]
dev = ["ipykernel>=6.29.5"]

[tool.ruff]
extend-exclude = ["notebooks/"]
